data_dir: /scratch2/data/cape_release
output_dir: /scratch2/projects/t4dt/logs/sweeps
model: '00032'
scene: longshort_flying_eagle
experiment_name: qtt_00032_longshort_flying_eagle_high_ranks_high_thr
decomposition: TT
num_sample_points: 30000
trunc_values: '[(-0.05, 0.05)]'
tt_ranks: [100]
