data_dir: /scratch2/data/cape_release
output_dir: /scratch2/projects/t4dt/logs/sweeps
model: '00032'
scene: longshort_flying_eagle
experiment_name: tt_tucker_00032_longshort_flying_eagle_ranks
decomposition: TT-Tucker
num_sample_points: 30000
trunc_values: '[(-0.05, 0.05)]'
max_inner_ranks: [64, 32, 16, 8]
tt_ranks: [128, 100, 50, 20, 10]
rank_multiplier: 2
