data_dir: /scratch2/data/cape_release
output_dir: /scratch2/projects/t4dt/logs/sweeps
model: '00032'
scene: longshort_flying_eagle
experiment_name: tt_tucker_00032_longshort_flying_eagle_ranks
decomposition: TT-Tucker
num_sample_points: 30000
trunc_values: '[(-0.5, 0.5), (-0.05, 0.05), (-0.01, 0.01), (-0.005, 0.005)]'
max_inner_ranks: [20, 50, 100]
tt_ranks: [1024, 512, 128]
